export const GET_PRACTICE = "GET_PRACTICE";
export const DELETE_PRACTICE = "DELETE_PRACTICE";
export const ADD_PRACTICE = "ADD_PRACTICE";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
