export const GET_TRICK = "GET_TRICK";
export const GET_TRICK_ONE = "GET_TRICK_ONE";
export const GET_PRACTICE = "GET_PRACTICE";
export const DELETE_PRACTICE = "DELETE_PRACTICE";
export const ADD_PRACTICE = "ADD_PRACTICE";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_SESSION = "GET_SESSION";
export const DELETE_SESSION = "DELETE_SESSION";
export const ADD_SESSION = "ADD_SESSION";