# Generated by Django 3.2 on 2021-04-26 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(null=True)),
                ('date', models.DateField(null=True)),
                ('summary', models.TextField()),
                ('note', models.TextField()),
                ('videolink', models.URLField()),
                ('video', models.FileField(upload_to='./VideoUpload')),
                ('practice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='practice.practice')),
            ],
        ),
    ]
