# Generated by Django 3.2 on 2021-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='video',
            field=models.FileField(null=True, upload_to='./VideoUpload'),
        ),
        migrations.AlterField(
            model_name='session',
            name='videolink',
            field=models.URLField(null=True),
        ),
    ]
